name: Deploy to EC2

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.15"

            - name: Install dependencies
              run: npm install

            - name: Load environment variables from .env
              id: load-env
              run: |
                  echo "Loading environment variables from .env file"
                  export $(grep -v '^#' .env | xargs)
                  echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV
                  echo "ECR_REPOSITORY=$ECR_REPOSITORY" >> $GITHUB_ENV
                  echo "ECS_SERVICE=$ECS_SERVICE" >> $GITHUB_ENV
                  echo "ECS_CLUSTER=$ECS_CLUSTER" >> $GITHUB_ENV
                  echo "ECS_TASK_DEFINITION=$ECS_TASK_DEFINITION" >> $GITHUB_ENV
                  echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV

            - name: Build project
              run: npm run build

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Copy files to EC2
              run: |
                  scp -r -o StrictHostKeyChecking=no ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/myapp

            - name: Deploy to EC2
              run: |
                  ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
                  cd /home/ubuntu/myapp
                  npm install
                  pm2 restart all || pm2 start npm --name "myapp" -- start
                  EOF
